{% set name = "anaconda-cloud" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud-{{ version }}.tar.gz
  sha256: c5b63cb8787b4c3bbf7a533141bcae1ec4992d476ea42c3f7dbca1808ad543d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8
    - anaconda-cloud-cli
    - anaconda-cloud-auth

test:
  imports:
    - anaconda_cloud
    - anaconda_cli_base
    - anaconda_cloud_auth
    - anaconda_cloud_cli
    - binstar_client
  commands:
    - anaconda --version
    - python -c "from anaconda_cloud import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: Anaconda Cloud client tools
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
